import { OriginalPhoto } from './OriginalPhoto'
import { site } from '@/data/site'
import { Shell, Footer, CTA } from './BrandShell'

type Item = { slug: string; title: string; name?: string; intro?: string; text?: string; detail?: string }
type Props = { kind: 'service' | 'zone'; item: Item; related: Item[] }
export function LongDetail({ kind, item, related }: Props) {
  const service = kind === 'service'
  const title = service ? `${item.title} a ${site.city}` : item.title
  const subject = item.name || site.city
  const description = item.detail || item.text || `Per un recupero a ${subject}, comunica il punto esatto, le condizioni del mezzo e la destinazione. Organizziamo il trasporto valutando accessi e situazione del veicolo.`
  return <Shell><main id="contenuto"><section className="detail-hero wrap"><nav className="breadcrumbs" aria-label="Percorso"><a href="/">Home</a><span aria-hidden="true">/</span><a href={service ? '/#servizi' : '/#territorio'}>{service ? 'Servizi' : 'Territorio'}</a><span aria-hidden="true">/</span><span>{item.title}</span></nav><h1>{title}</h1><p className="detail-lead">{description}</p><CTA />{service ? <div className="detail-image"><OriginalPhoto name={item.slug} alt={item.title} priority /></div> : <div className="territory-cover"><span className="eyebrow">Emilia-Romagna / Soccorso sul territorio</span><h2>{subject}</h2><span className="territory-caption">Recupero · Trasporto · Assistenza</span></div>}</section><section className="section wrap detail-body"><aside className="detail-aside"><span className="eyebrow">Emilia-Romagna / Assistenza</span><h3 style={{marginTop:20}}>Partiamo dai dettagli.</h3><p>Posizione, modello del veicolo e problema. Tieni queste informazioni a portata di mano quando ci contatti.</p><CTA /></aside><article><h2>{service ? 'Un intervento costruito sulla situazione.' : `Il recupero, a ${subject}.`}</h2><p>{description}</p><p>Un parcheggio, una strada trafficata o un accesso privato richiedono preparazioni diverse. Indica se le ruote girano, se il mezzo può essere messo in folle e se ci sono ostacoli al carico. Non è necessario fare una diagnosi: descrivi semplicemente ciò che osservi.</p><h2 style={{marginTop:45}}>Il costo si chiarisce prima.</h2><p>La distanza, le condizioni del recupero, la tipologia del veicolo e la destinazione incidono sul preventivo. Concordiamo questi dettagli prima di confermare il servizio, così puoi decidere conoscendo le modalità dell’intervento.</p><h2 style={{marginTop:45}}>Dove vuoi portare il mezzo?</h2><p>Puoi indicare la tua officina, una carrozzeria o un’altra destinazione concordata. La consegna viene organizzata insieme al recupero, considerando gli orari di accesso e le condizioni del luogo.</p><p>{service ? `Per ${item.title.toLowerCase()} in zona ${site.city}, invia la posizione e i dettagli del veicolo per verificare la disponibilità.` : `Per le richieste nella zona di ${subject}, specifica anche un riferimento riconoscibile e lo spazio disponibile per avvicinare il mezzo di soccorso.`}</p></article></section><section className="section wrap"><div className="section-top"><h2>{service ? 'Altri servizi.' : 'Nei dintorni.'}</h2><a className="text-link" href="/">Torna alla home ↗</a></div><div className="related">{related.filter(entry => entry.slug !== item.slug).slice(0,6).map(entry => <a data-reveal key={entry.slug} href={`/${service ? 'servizi' : 'zone'}/${entry.slug}/`}><h3>{entry.title}</h3><span className="text-link">Scopri di più ↗</span></a>)}</div></section></main><Footer /></Shell>
}
